TABLES: ytsd_cab_pedido.

SELECTION-SCREEN BEGIN OF SCREEN: 110 AS SUBSCREEN. "FILTROS

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-001.

  SELECT-OPTIONS: fil_num FOR ytsd_cab_pedido-numero_pedido,
                  fil_data FOR ytsd_cab_pedido-data_pedido.

  SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN END OF SCREEN 110.


SELECTION-SCREEN BEGIN OF SCREEN: 120 AS SUBSCREEN. "MODIFICACAO

SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-002.

  PARAMETERS: mod_num TYPE ytsd_cab_pedido-numero_pedido,
              mod_data TYPE ytsd_cab_pedido-data_pedido,
              mod_canc AS CHECKBOX DEFAULT ''.


  SELECTION-SCREEN END OF BLOCK b2.

  SELECTION-SCREEN PUSHBUTTON 1(15) mod_btn USER-COMMAND modify_reg.

 SELECTION-SCREEN END OF SCREEN 120.


SELECTION-SCREEN BEGIN OF TABBED BLOCK tab_screen FOR 8 LINES.

  SELECTION-SCREEN TAB (20) filter USER-COMMAND filter_evnt DEFAULT SCREEN 110.
  SELECTION-SCREEN TAB (30) modify USER-COMMAND modify_evnt DEFAULT SCREEN 120.

  SELECTION-SCREEN END OF BLOCK tab_screen.